### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by ackleyd1** [ackleyd1/MI-449-SS17-740-html-terminal-and-git-_u9ftI#1]
@egillespie Can you take a look at this? It's [hosted here](https://ackleyd1.github.io/MI-449-SS17-740-html-terminal-and-git-_u9ftI/) and meets the following criteria:

- [x] A knock-knock joke is displayed when visiting the website
- [x] The code is pushed to GitHub
- [x] The website is hosted on GitHub Pages

**Comment by egillespie** [comment]
Nicely done. Cereal pleasure to see you again! :shipit:

**Comment by ackleyd1** [comment]
HA! Thanks Erik 👍  same to you!

**Comment by egillespie** [comment]
:bowing_man:
